import type { DefaultTheme } from "vitepress";

// Generated by scripts/gen-package-pages.ts. Do not edit — run
// `bun run docs:packages` instead.
export const packagesSidebar: DefaultTheme.SidebarItem[] = [
  {
    text: "Overview",
    items: [{ text: "All packages", link: "/packages/" }],
  },
  {
    text: "Engine",
    collapsed: false,
    items: [
      { text: "@smartput/core", link: "/packages/core" },
      { text: "@smartput/kind", link: "/packages/kind" },
      { text: "@smartput/kinds", link: "/packages/kinds" },
      { text: "@smartput/shared", link: "/packages/shared" },
      { text: "@smartput/smartputs", link: "/packages/smartputs" },
    ],
  },
  {
    text: "Kinds",
    collapsed: false,
    items: [
      { text: "@smartput/angle", link: "/packages/angle" },
      { text: "@smartput/area", link: "/packages/area" },
      { text: "@smartput/boolean", link: "/packages/boolean" },
      { text: "@smartput/datarate", link: "/packages/datarate" },
      { text: "@smartput/datasize", link: "/packages/datasize" },
      { text: "@smartput/duration", link: "/packages/duration" },
      { text: "@smartput/energy", link: "/packages/energy" },
      { text: "@smartput/length", link: "/packages/length" },
      { text: "@smartput/mass", link: "/packages/mass" },
      { text: "@smartput/measure", link: "/packages/measure" },
      { text: "@smartput/number", link: "/packages/number" },
      { text: "@smartput/percent", link: "/packages/percent" },
      { text: "@smartput/power", link: "/packages/power" },
      { text: "@smartput/speed", link: "/packages/speed" },
      { text: "@smartput/temperature", link: "/packages/temperature" },
      { text: "@smartput/tempo", link: "/packages/tempo" },
      { text: "@smartput/volume", link: "/packages/volume" },
    ],
  },
  {
    text: "Money",
    collapsed: false,
    items: [
      { text: "@smartput/currency", link: "/packages/currency" },
      { text: "@smartput/rate", link: "/packages/rate" },
    ],
  },
  {
    text: "Dates and time",
    collapsed: false,
    items: [
      { text: "@smartput/date", link: "/packages/date" },
      { text: "@smartput/datetime", link: "/packages/datetime" },
      { text: "@smartput/holiday", link: "/packages/holiday" },
      { text: "@smartput/time", link: "/packages/time" },
      { text: "@smartput/timezone", link: "/packages/timezone" },
    ],
  },
  {
    text: "Ranges",
    collapsed: false,
    items: [
      { text: "@smartput/date-range", link: "/packages/date-range" },
      { text: "@smartput/datetime-range", link: "/packages/datetime-range" },
      { text: "@smartput/range", link: "/packages/range" },
      { text: "@smartput/range-core", link: "/packages/range-core" },
      { text: "@smartput/time-range", link: "/packages/time-range" },
    ],
  },
  {
    text: "Places",
    collapsed: false,
    items: [
      { text: "@smartput/distance", link: "/packages/distance" },
      { text: "@smartput/geo", link: "/packages/geo" },
    ],
  },
  {
    text: "Math and queries",
    collapsed: false,
    items: [
      { text: "@smartput/math", link: "/packages/math" },
      { text: "@smartput/query", link: "/packages/query" },
    ],
  },
];

export default packagesSidebar;
