// Generated facade over `@smartput/core` — see `packages/smartputs/README.md` for why
// this package exists, and `parity.test.ts` for what keeps this list honest.
//
// The runtime names are spelled out rather than star-re-exported, and that is
// not a style preference. `export * from` an external package survives into
// `dist` as a star, and a consumer bundling a named import against that dist
// gets "No matching export" — the failure `@smartput/core`'s own `errors.ts`
// carries a comment about, hit for real during the kind extraction.
// `export type *` is safe by contrast: it emits nothing at all, so no star is
// left in the JavaScript.

export type * from "@smartput/core";
export {
  AmbiguityError,
  Autocompleter,
  aliasesFor,
  BOOLEAN_KIND,
  BOOLEAN_UNIT,
  buildKeywords,
  buildProgram,
  buildRegistry,
  COMPARE_PRECISION,
  COMPARISON_OPS,
  CUE_CEILING,
  cardinalNumerals,
  cardinalSpeller,
  collectCues,
  complete,
  composeLocale,
  compoundSplitter,
  createAnalyzerChain,
  createCachedEngine,
  createEngine,
  createFacade,
  createFacades,
  createSnapshotCache,
  DEFAULT_CUE_WINDOW,
  DEFAULT_MAX_SPAN,
  Decimal,
  DISPLAY_PRECISION,
  DimensionMismatchError,
  DivideByZeroError,
  decimalRatios,
  defineKind,
  defineLanguage,
  defineVocabulary,
  deriveValue,
  EDIT_HEADROOM,
  Evaluator,
  EXACT_BONUS,
  editDistance,
  evaluateNode,
  foldLiterals,
  formatNumber,
  formatValue,
  generateComparisonOps,
  identity,
  KeywordConflictError,
  KindConflictError,
  LENGTH_PENALTY,
  LocaleMismatchError,
  MissingRateError,
  NoCandidateError,
  Normalizer,
  NUMBER_FALLBACK_WEIGHT,
  NUMBER_KIND,
  nearestWord,
  normalize,
  Parser,
  PERCENT_KIND,
  Printer,
  phraseAnalyzer,
  prefixStripper,
  RateProviderError,
  RatesNotReadyError,
  SCALE_BONUS,
  Scanner,
  SmartputError,
  Solver,
  scriptSegmenter,
  solve,
  suffixStripper,
  Tokenizer,
  TooAmbiguousError,
  tableAnalyzer,
  UnitParseError,
  UnknownKindError,
  VocabularyConflictError,
  walk,
  wordsFor,
} from "@smartput/core";
