import type { CountryRow } from "./kind/types";
import { PlaceProviderError } from "./place";
import type { GeoCountry, GeoNames } from "./providers/geonames";

/**
 * The country table, assembled from GeoNames instead of committed.
 *
 * This module is the whole point of the package. What it replaces was 5 265
 * lines of generated TypeScript regenerated by hand from a monthly export, plus
 * a second copy of every name for every language anyone wanted to support. What
 * it costs is two kinds of request and one join.
 *
 * **Why two.** No single GeoNames endpoint carries a whole country row, and the
 * two halves are missing from each other in opposite directions:
 *
 * - `countryInfoJSON` is the *table*: alpha-3, capital, currency, area,
 *   population, and the postal mask. It carries no coordinates, no timezone and
 *   no names but the one.
 * - A country's own **feature** row — the `PCLI`/`TERR` entry that
 *   `childrenJSON` walks to — is the *place*: latitude, longitude, timezone,
 *   and `alternateNames`, which is where "uk", "usa", "holland" and the whole
 *   of the internationalization live.
 *
 * Neither is optional. Without the first there is no currency for the rates
 * bridge; without the second there is no zone for the datetime bridge and no
 * alias but the official name, so `uk` stops resolving.
 *
 * **What is asked for and what it costs.** One `countryInfoJSON`, one
 * `childrenJSON` for Earth, and one per continent — nine requests against a free
 * account's hourly thousand. Then the join, by alpha-2.
 */

/** GeoNames' id for the Earth feature, the root of the administrative tree. */
const EARTH = 6295630;

export interface CountryTableOptions {
  /**
   * BCP 47. Decides the language of `name` and of the aliases, and is the only
   * knob this package has for internationalization — because it is the only one
   * it needs. GeoNames holds the names; nothing here translates anything.
   */
  readonly lang?: string;
  /**
   * Alternate-name language tags kept as aliases, beyond `lang` itself.
   *
   * The defaults are GeoNames' pseudo-languages for the non-linguistic names:
   * `abbr` is where "UK" and "USA" live, `iso` and `fips` are the code systems,
   * and an entry with no tag at all is an unattributed alternate spelling. They
   * are kept for every `lang`, because "USA" is "USA" in Ukrainian too.
   *
   * `link` is deliberately absent: those entries are URLs.
   */
  readonly aliasLanguages?: readonly string[];
  readonly signal?: AbortSignal;
}

const DEFAULT_ALIAS_LANGUAGES: readonly string[] = ["", "abbr", "iso", "fips"];

/** Shortest alias that may be indexed, unless it is the alpha-2 itself. */
const MIN_ALIAS_LENGTH = 3;

/** At most this many words, which is what the matcher's trie will walk. */
const MAX_ALIAS_WORDS = 4;

/**
 * Derive a regex from GeoNames' human-readable postal mask.
 *
 * `countryInfoJSON` publishes `postalCodeFormat` — `@## #@@` for the United
 * Kingdom, `#####-####` for the United States — and stops there; the
 * `postalCodeRegex` column exists only in the `countryInfo.txt` export. Deriving
 * one from the other is a four-character substitution, and it is honest about
 * what it produces: a mask is a shape, so the regex it becomes is a shape check
 * and not upstream's hand-tuned pattern. `PostalFormat` uses it for exactly
 * that.
 *
 * `#` is a digit, `@` is a letter, `.` in a mask is a literal dot, and a space
 * is optional because half the world writes postcodes without one. Anything else
 * is escaped and kept.
 */
export function regexFromMask(mask: string): string {
  const trimmed = mask.trim();
  if (trimmed === "") return "";
  let out = "";
  for (const ch of trimmed) {
    if (ch === "#") out += "\\d";
    else if (ch === "@") out += "[A-Za-z]";
    else if (ch === " ") out += "\\s?";
    else out += ch.replace(/[.*+?^${}()|[\]\\]/, "\\$&");
  }
  return `^${out}$`;
}

/**
 * Fold one alternate name to an alias, or null if it may not be one.
 *
 * The refusals are the matcher's, applied here rather than there for the reason
 * the generated tables applied them at build: the literal fold is destructive,
 * and a rule enforced at match time is one `if` away from being skipped. A
 * two-letter alias would be the whole ISO code space plus most of the unit
 * vocabulary — "km" is a kilometre before it is Comoros.
 */
function toAlias(name: string, a2: string): string | null {
  const folded = name.trim().toLowerCase().replace(/\s+/g, " ");
  if (folded === "") return null;
  if (folded === a2) return folded;
  if (folded.length < MIN_ALIAS_LENGTH) return null;
  if (folded.split(" ").length > MAX_ALIAS_WORDS) return null;
  return folded;
}

/** One country's feature row, as `childrenJSON` under `style=FULL` gives it. */
export interface CountryFeature {
  readonly countryCode: string;
  readonly name: string;
  readonly lat: number;
  readonly lon: number;
  readonly zone: string;
  readonly aliases: readonly string[];
}

/**
 * Join a country's table row and its feature row into the row the kind is built
 * from.
 *
 * Exported and pure, so the join is testable without a client — which matters
 * more here than anywhere else in the package, because this is the function that
 * decides what every place Value in a consumer's engine is made of.
 *
 * A country present in one half and not the other is **dropped**, not filled in.
 * A row with no coordinates would break the distance op silently and a row with
 * no zone would break the datetime bridge silently; a country that is simply
 * absent is a miss the caller can see.
 */
export function joinCountries(
  table: readonly GeoCountry[],
  features: readonly CountryFeature[],
): CountryRow[] {
  const byA2 = new Map<string, CountryFeature>(
    features.map((f) => [f.countryCode.toLowerCase(), f]),
  );

  const rows: CountryRow[] = [];
  for (const country of table) {
    const feature = byA2.get(country.a2);
    if (feature === undefined) continue;

    // The alpha-2 and alpha-3 are aliases in their own right: a code written as
    // a code has to resolve, and the trie is where it may, because it can refuse
    // a claim by neighbour in a way the global alias index cannot.
    const aliases = new Set<string>();
    for (const candidate of [country.name, ...feature.aliases, country.a3, country.a2]) {
      const alias = toAlias(candidate, country.a2);
      if (alias !== null) aliases.add(alias);
    }

    rows.push({
      a2: country.a2,
      a3: country.a3,
      name: country.name,
      aliases: [...aliases],
      capital: country.capital,
      currency: country.currency,
      phone: "",
      population: country.population,
      area: country.area,
      lat: feature.lat,
      lon: feature.lon,
      zone: feature.zone,
      geonameId: country.geonameId,
      postalRegex: regexFromMask(country.postalFormat),
    });
  }
  return rows;
}

/**
 * Every country GeoNames holds, as `CountryRow`s, in the language asked for.
 *
 * ```ts
 * const gn = geonames({ username });
 * const countries = await countryTable(gn, { lang: "uk" });
 * const kind = definePlace({ countries });
 * ```
 *
 * Nothing here is cached. The account's credits are the consumer's to spend and
 * the TTL that spends them belongs to `createLivePlace`, not to a function that
 * cannot know how often it is called — the same ruling `geonames()` itself
 * carries.
 */
export async function countryTable(
  client: GeoNames,
  opts: CountryTableOptions = {},
): Promise<CountryRow[]> {
  const query = {
    text: "",
    ...(opts.lang === undefined ? {} : { lang: opts.lang }),
    ...(opts.signal === undefined ? {} : { signal: opts.signal }),
  };

  const [table, features] = await Promise.all([
    client.countries(query),
    countryFeatures(client, opts),
  ]);

  const rows = joinCountries(table, features);
  if (rows.length === 0) {
    // Loud, because the alternative is a kind with no units: an engine that
    // silently stops recognising every country name in the world reads to a
    // consumer as "the parser broke", which is the wrong place to go looking.
    throw new PlaceProviderError(
      client.id,
      "no country appeared in both countryInfo and the feature tree — the join found nothing",
    );
  }
  return rows;
}

/**
 * The country features, by walking Earth's children and then each continent's.
 *
 * Two levels and not one, because GeoNames' tree has continents in between and
 * `searchJSON` cannot stand in: it requires a query string, so "every country"
 * is not a search it can express. Nine requests is the cost of the only route
 * upstream offers.
 *
 * Continents are fetched in parallel and a continent that fails takes only its
 * own countries with it — Antarctica returning nothing must not cost the caller
 * Europe.
 */
async function countryFeatures(
  client: GeoNames,
  opts: CountryTableOptions,
): Promise<CountryFeature[]> {
  const langs = new Set(opts.aliasLanguages ?? DEFAULT_ALIAS_LANGUAGES);
  if (opts.lang !== undefined) langs.add(opts.lang);

  const query = {
    text: "",
    limit: 1000,
    ...(opts.lang === undefined ? {} : { lang: opts.lang }),
    ...(opts.signal === undefined ? {} : { signal: opts.signal }),
  };

  const continents = await client.children(EARTH, query);
  const settled = await Promise.allSettled(
    continents.map((continent) => client.children(continent.place.geonameId, query)),
  );

  const out: CountryFeature[] = [];
  for (const result of settled) {
    if (result.status !== "fulfilled") continue;
    for (const node of result.value) {
      if (node.place.country === "") continue;
      out.push({
        countryCode: node.place.country,
        name: node.place.name,
        lat: node.place.lat,
        lon: node.place.lon,
        zone: node.place.zone,
        aliases: node.alternateNames.filter((n) => langs.has(n.lang)).map((n) => n.name),
      });
    }
  }
  return out;
}
