/**
 * `@smartput/boolean` — what a comparison returns.
 *
 * The kind is registered like any other and generates no operations of its
 * own; the six comparison signatures that *produce* a boolean are generated by
 * core, per kind, beside the arithmetic ones. So this package is a kind, a
 * formatter and two ways to read the result — and registering it is what turns
 * `1000 mb = 1 gb` from an unresolvable expression into `true`.
 */
export {
  BOOLEAN_KIND,
  BOOLEAN_UNIT,
  boolean,
  booleanValue,
  truthOf,
} from "./boolean";
export { Bool } from "./class";
