import { composeLocale, createEngine } from "@smartput/core";
import { english as en } from "@smartput/core/locale/en";
import { BUILTIN_KINDS } from "@smartput/kinds";
import BUILTIN_EN from "@smartput/kinds/locale/en";

const engine = createEngine({
  locales: [composeLocale(en, BUILTIN_EN)],
  kinds: BUILTIN_KINDS,
});

const INPUTS = [
  // The bridges. Every one of these needs two kinds registered at once, which
  // is the whole reason this package exists.
  "3 m * 4 m",
  "1 km * 1 km",
  "100 km / 2 h",
  "1 km / 1 min",
  "2 kw * 3 h",
  "3 h * 2 kw",
  "1 kwh / 1 h",
  "1 kwh / 1 kw",
  "500 mb / 20 s",
  "100 mbps * 1 min",
  "1 min * 100 mbps",
  "1 gb / 100 mbps",
  "120 bpm in ms",
  "500 ms in bpm",
  // Comparisons — generated by core per kind, and unresolvable without
  // `boolean` registered beside them.
  "1000 mb = 1 gb",
  "1 mi > 1 km",
  "100 kph < 60 mph",
  "1 kwh = 3.6 mj",
  // Cross-unit arithmetic inside one kind, and the number/percent forms.
  "1 kg + 500 g",
  "30 h - 30 min",
  "212 F in C",
  "30 C - 20 C",
  "20% of 50",
  "50 + 20%",
  "(1 + 2) * 3",
  "one thousand thirty two",
  "1 kib in b",
  "90 deg in rad",
  "1 hectare in m2",
  "1 gal in l",
];

for (const input of INPUTS) {
  try {
    const r = engine.evaluate(input);
    console.log(`${input}\t${r.kind}\t${r.value.canonical.toString()}\t${r.formatted}`);
  } catch (e) {
    console.log(
      `${input}\tERROR\t${(e as Error).constructor.name}\t${(e as Error).message}`,
    );
  }
}
