/**
 * Regenerates every `packages/<kind>/corpus/uk.tsv`.
 *
 * ```sh
 * bun run packages/kinds/.scratch/gen-uk.ts
 * ```
 *
 * It lives here, in the one package that already depends on all the others, so
 * that a single file can build each package's corpus engine *exactly* as that
 * package's own `corpus.test.ts` builds it — same kinds, same vocabularies,
 * nothing else. If the two ever drift, the corpus stops describing the package.
 *
 * The inputs and the `#` lines between them are written by hand: choosing the
 * rows is the whole work, and they are the claim the file makes. The three
 * answer columns are read back off the engine, because a formatted Ukrainian
 * string carries U+00A0 grouping and a decimal comma that are invisible in a
 * diff and unretypeable by hand. What makes the result a test rather than a
 * recording is that every generated row was read and approved before it landed
 * — the same rule `packages/core/corpus/uk.tsv` was written under, which is how
 * that file arrived carrying two rows marked KNOWN WRONG instead of blessed.
 */
import { angle } from "@smartput/angle";
import angleUk from "@smartput/angle/locale/uk";
import { area } from "@smartput/area";
import areaUk from "@smartput/area/locale/uk";
import { composeLocale, createEngine, type Engine } from "@smartput/core";
import { ukrainian as uk } from "@smartput/core/locale/uk";
import { datarate } from "@smartput/datarate";
import datarateUk from "@smartput/datarate/locale/uk";
import { datasize } from "@smartput/datasize";
import datasizeUk from "@smartput/datasize/locale/uk";
import { duration } from "@smartput/duration";
import durationUk from "@smartput/duration/locale/uk";
import { energy } from "@smartput/energy";
import energyUk from "@smartput/energy/locale/uk";
import { length } from "@smartput/length";
import lengthUk from "@smartput/length/locale/uk";
import { mass } from "@smartput/mass";
import massUk from "@smartput/mass/locale/uk";
import { number } from "@smartput/number";
import numberUk from "@smartput/number/locale/uk";
import { percent } from "@smartput/percent";
import percentUk from "@smartput/percent/locale/uk";
import { power } from "@smartput/power";
import powerUk from "@smartput/power/locale/uk";
import { speed } from "@smartput/speed";
import speedUk from "@smartput/speed/locale/uk";
import { tempdelta, temperature } from "@smartput/temperature";
import temperatureUk from "@smartput/temperature/locale/uk";
import { tempo } from "@smartput/tempo";
import tempoUk from "@smartput/tempo/locale/uk";
import { volume } from "@smartput/volume";
import volumeUk from "@smartput/volume/locale/uk";
import { BUILTIN_KINDS } from "../src/index";
import BUILTIN_UK from "../src/locale/uk";

const HEADER = "# input\tkind\tcanonical\tformatted";

/** The plural block every ratio kind gets, since every one of them can express it. */
const CORPORA: { pkg: string; engine: Engine; lines: string[] }[] = [
  {
    pkg: "angle",
    engine: createEngine({
      locales: [composeLocale(uk, [numberUk, angleUk])],
      kinds: [number, angle],
    }),
    lines: [
      HEADER,
      "90 градусів",
      "90 градусів в радіанах",
      "0,25 об в градусах",
      "200 град в градусах",
      "90 градусів + 90 градусів",
      "1 оберт - 90 градусів",
      "45 градусів * 2",
      "180 градусів / 4",
      "-90 градусів",
      "1 радіан в градусах",
      "один оберт",
      "360 градусів в обертах",
      "1,5 радіана",
      "100 гон в град",
      "2 оберти в градусах",
      "# The four plural categories, which English has two of: 21 is singular in",
      "# Ukrainian and 11 is not, and the fractional row is the genitive",
      '# *singular* — "1,5 градуса", never "1,5 градусів".',
      "21 градус",
      "11 градусів",
      "2 градуси",
      "1,5 градуса",
    ],
  },
  {
    pkg: "area",
    engine: createEngine({
      locales: [composeLocale(uk, [numberUk, lengthUk, areaUk])],
      kinds: [number, length, area],
    }),
    lines: [
      HEADER,
      "3 м * 4 м",
      "1 гектар в м2",
      "1 акр в м2",
      "2 км2 в гектарах",
      "5000 см2 в м2",
      "10 м2 + 5 м2",
      "1 гектар - 2500 м2",
      "3 м2 * 4",
      "100 м2 / 4",
      "-5 м2",
      "2 км2 в м2",
      "1 м2 в см2",
      "два гектари",
      "1 км * 1 км",
      "12 м2",
      "# The squared units print as a symbol in both languages, so the rows that",
      "# separate the two are the hectare's — a declined noun with four plural",
      '# categories where English has "hectares" and nothing else.',
      "21 гектар",
      "11 гектарів",
      "2 гектари",
      "1,5 гектара",
      "5 гектарів",
    ],
  },
  {
    pkg: "boolean",
    engine: createEngine({
      locales: [composeLocale(uk, BUILTIN_UK)],
      kinds: BUILTIN_KINDS,
    }),
    lines: [
      "# What a comparison returns. Registering this kind is what turns",
      "# `1000 мб = 1 гб` from an unresolvable expression into `true`.",
      "#",
      "# `true` and `false` are not translated, and that is this file's finding",
      "# rather than an oversight it hides: the kind ships no vocabulary at all,",
      "# so `formatValue` degrades to the unit key in every language. A Ukrainian",
      '# engine answering "true" is what the code does today, and a row asserting',
      "# it is what makes a later `boolean/locale/uk` a visible diff here.",
      HEADER,
      "1000 мб = 1 гб",
      "1 км > 999 м",
      "1 км < 999 м",
      "1 м = 100 см",
      "1 кг = 1 кг",
      "2 > 1",
      "1 >= 1",
      "1 <= 0",
      "5 != 4",
      "1 гб = 1000 мб",
      "1 миля > 1 км",
      "3 < 4",
      "10 = 10",
      "1 кіб > 1 кб",
      "0 < 1",
      "20 C > 10 C",
      "1 гектар = 10000 м2",
      "1 kwh = 3,6 МДж",
      "1 год != 60 хв",
      '# The decimal comma on both sides of a comparison: "3,6" is one number in',
      "# Ukrainian and would be two arguments in English.",
      "3,6 МДж = 1 kwh",
    ],
  },
  {
    pkg: "datarate",
    engine: createEngine({
      locales: [composeLocale(uk, [numberUk, durationUk, datasizeUk, datarateUk])],
      kinds: [number, duration, datasize, datarate],
    }),
    lines: [
      HEADER,
      "100 мбіт",
      "1 гбіт в мбіт",
      "500 мб / 20 с",
      "100 мбіт * 1 хв",
      "1 хв * 100 мбіт",
      "1 гб / 100 мбіт",
      "100 мбіт + 50 мбіт",
      "1 тбіт в гбіт",
      "2 мбіт * 3",
      "1 гбіт / 4",
      "-10 мбіт",
      "8000 біт в кбіт",
      "один гбіт",
      "1 гбіт в біт",
      "250 мбіт",
      "# `біт` and `байт` are one letter apart in Cyrillic and name two different",
      "# kinds — a rate and a size. These two rows are the pair that would catch a",
      "# vocabulary that let one fold onto the other.",
      "100 мегабіт",
      "100 мегабайт",
    ],
  },
  {
    pkg: "datasize",
    engine: createEngine({
      locales: [composeLocale(uk, [numberUk, datasizeUk])],
      kinds: [number, datasize],
    }),
    lines: [
      HEADER,
      "1 кіб в б",
      "1 гб в мб",
      "1 гіб в міб",
      "1 тб в гб",
      "500 мб + 500 мб",
      "1 гб - 200 мб",
      "2 гб * 3",
      "1 тб / 4",
      "-1 гб",
      "1024 б в кіб",
      "один гігабайт",
      "1 міб в кб",
      "3 терабайти",
      "1 гб в б",
      "1500 байтів",
      "# The four plural categories on the byte, and the fraction that takes the",
      "# genitive singular rather than a plural.",
      "21 байт",
      "11 байтів",
      "2 байти",
      "1 гб - 500 мб",
    ],
  },
  {
    pkg: "duration",
    engine: createEngine({
      locales: [composeLocale(uk, [numberUk, durationUk])],
      kinds: [number, duration],
    }),
    lines: [
      HEADER,
      "2 тиж",
      "30 год - 30 хв",
      "90 хв в год",
      "1 д в год",
      "1 тиж в днях",
      "500 мс + 500 мс",
      "2 год * 3",
      "1 д / 4",
      "-2 год",
      "1 год в с",
      "одна година",
      "3600 с в год",
      "45 хвилин",
      "1,5 год в хв",
      "2 дні + 12 годин",
      "# `година` is feminine and `день` is masculine, so their paradigms are two",
      "# different decisions rather than one applied twice — and the fractional",
      "# category is the genitive singular in both.",
      "21 година",
      "11 годин",
      "2 години",
      "1 год + 30 хв",
      "21 день",
      "2 дні",
      "5 днів",
    ],
  },
  {
    pkg: "energy",
    engine: createEngine({
      locales: [composeLocale(uk, [numberUk, durationUk, powerUk, energyUk])],
      kinds: [number, duration, power, energy],
    }),
    lines: [
      HEADER,
      "1 kwh в Дж",
      "2 кВт * 3 год",
      "3 год * 2 кВт",
      "1 kwh / 1 год",
      "1 kwh / 1 кВт",
      "1 ккал в Дж",
      "1 btu в Дж",
      "1 МДж в кДж",
      "500 Дж + 500 Дж",
      "2 кДж * 3",
      "1 mwh в kwh",
      "-1 kwh",
      "один кілоджоуль",
      "1000 кал в ккал",
      "2,5 kwh",
      "# The watt-hour's Ukrainian symbol is `кВт·год`, a middle dot rather than",
      "# an operator, so it is one word token and reads as a unit — which is what",
      "# this row is here to hold. `kwh` above is the Latin alias for the same",
      "# unit, and the two must land on the same quantity.",
      "1 кВт·год в Дж",
      "# The declined joule, all four categories.",
      "21 джоуль",
      "11 джоулів",
      "2 джоулі",
      "500 Дж + 250 Дж",
    ],
  },
  {
    pkg: "kinds",
    engine: createEngine({
      locales: [composeLocale(uk, BUILTIN_UK)],
      kinds: BUILTIN_KINDS,
    }),
    lines: [
      "# The aggregator's corpus, so the rows are chosen for what only the whole",
      "# set can answer: the bridges between two kinds, and the comparisons that",
      "# need `boolean` registered beside the kind being compared. Each of the",
      "# four bridge owners names its operands by id string rather than importing",
      "# them, so a signature whose operands are unregistered is unreachable",
      "# rather than a build error — these rows are what would catch that.",
      "#",
      "# In Ukrainian they also answer a second question: a bridge resolves on a",
      "# *signature*, and a signature is reached through whichever language's",
      "# words got there. `500 мб / 20 с` proves the datasize÷duration bridge is",
      "# reachable from Cyrillic, which no English row can say.",
      HEADER,
      "3 м * 4 м",
      "1 км * 1 км",
      "100 км / 2 год",
      "1 км / 1 хв",
      "2 кВт * 3 год",
      "3 год * 2 кВт",
      "1 kwh / 1 год",
      "1 kwh / 1 кВт",
      "500 мб / 20 с",
      "100 мбіт * 1 хв",
      "1 хв * 100 мбіт",
      "1 гб / 100 мбіт",
      "120 бпм в мс",
      "500 мс в бпм",
      "1000 мб = 1 гб",
      "1 миля > 1 км",
      "1 kwh = 3,6 МДж",
      "1 кг + 500 г",
      "30 год - 30 хв",
      "212 F в C",
      "30 C - 20 C",
      "20% від 50",
      "50 + 20%",
      "(1 + 2) * 3",
      "одна тисяча тридцять два",
      "1 кіб в б",
      "90 градусів в радіанах",
      "1 гектар в м2",
      "1 гал в л",
      "# `км/год` is a written symbol and an expression at once: the lexer ends",
      "# the word token at the slash, so this is length ÷ duration reaching the",
      "# speed bridge, and it is how a Ukrainian reader writes a speed.",
      "120 км/год",
    ],
  },
  {
    pkg: "length",
    engine: createEngine({
      locales: [composeLocale(uk, [numberUk, lengthUk])],
      kinds: [number, length],
    }),
    lines: [
      HEADER,
      "10 км",
      "12 дюймів",
      "2 км в метрах",
      "1 миля в кілометрах",
      "10 м + 5 км",
      "1 км - 250 м",
      "10 км * 3",
      "1 км / 4",
      "-5 км",
      "3 фути в сантиметрах",
      "один кілометр",
      "1 ярд в сантиметрах",
      "1 500 мм в метрах",
      "5280 футів в милях",
      "двісті п'ять км",
      "# The four plural categories on one unit, which English has two of. 21 is",
      "# singular in Ukrainian and 11 is not, and neither follows from the other.",
      "21 метр",
      "11 метрів",
      "2 метри",
      "5 метрів",
      '# The fractional category, which is the genitive *singular* — "1,5',
      '# кілометра", never "1,5 кілометрів". No English row can express it.',
      "1 км + 500 м",
      "1,5 м",
      "# The feminine unit, where the nominative plural and the genitive singular",
      '# coincide ("2 милі", "1,5 милі") while the masculine ones diverge, and',
      "# the genitive plural is the bare stem rather than an -ів ending.",
      "2 милі",
      "5 миль",
      "# Latin aliases still read on a Ukrainian engine: `aliasesFor` reuses the",
      "# one alias map in units.ts, so a developer typing `km` is understood.",
      "2 km",
    ],
  },
  {
    pkg: "mass",
    engine: createEngine({
      locales: [composeLocale(uk, [numberUk, massUk])],
      kinds: [number, mass],
    }),
    lines: [
      HEADER,
      "1 кг + 500 г",
      "3 фунти",
      "1 500 г",
      "1 т в кг",
      "16 унцій в фунтах",
      "1 кг в г",
      "2 кг - 500 г",
      "3 кг * 4",
      "1 т / 8",
      "-2 кг",
      "500 мг в г",
      "один кілограм",
      "2,5 тонни в кг",
      "1 фунт в унціях",
      "1,5 кілограма",
      '# The pair English cannot write at all: "1 500 г" is fifteen hundred grams',
      '# typed with the group separator and "1,5 кілограма" is one and a half',
      '# kilograms typed with the decimal comma. In English "1,500 g" is the',
      "# first of those and there is no spelling that collides with it.",
      "1,5 кг",
      "# `тонна` is feminine where `кілограм` is masculine, so the two paradigms",
      "# diverge exactly where a hand-pasted one would look right and be wrong.",
      "21 тонна",
      "11 тонн",
      "2 тонни",
      "21 кілограм",
      "2 кілограми",
    ],
  },
  {
    pkg: "number",
    engine: createEngine({
      locales: [composeLocale(uk, [numberUk])],
      kinds: [number],
    }),
    lines: [
      HEADER,
      "(1 + 2) * 3",
      "1 + 1",
      "10 - 4",
      "6 * 7",
      "10 / 4",
      "-5",
      "1 500",
      "одна тисяча тридцять два",
      "двісті п'ять",
      "0,1 + 0,2",
      "2 * 3 * 7",
      "1234567890123456789",
      "3 * (4 + 5)",
      "100 / 3",
      "дев'ять",
      "# The two rows that make this file worth having beside en.tsv. Ukrainian",
      '# reads "," as the decimal mark, so "1,5" is one number here and two',
      "# arguments in English — and the group separator it prints is U+00A0,",
      "# which is not the space it accepts on the way in.",
      "1,5 + 1,5",
      "1 500 + 500",
      "# The hundreds are table entries rather than compositions: `двісті` is not",
      "# `два сто` and `п'ятсот` is one fused word. The apostrophe inside the",
      "# numeral is part of the word token, which the lexer had to be taught.",
      "п'ятсот",
      "дев'ятсот дев'яносто дев'ять",
    ],
  },
  {
    pkg: "percent",
    engine: createEngine({
      locales: [composeLocale(uk, [numberUk, percentUk])],
      kinds: [number, percent],
    }),
    lines: [
      HEADER,
      "20% від 50",
      "50 + 20%",
      "50 - 10%",
      "10%",
      "10% + 5%",
      "100 * 20%",
      "1 у відсотках",
      "0,5 у відсотках",
      "200%",
      "-10%",
      "15% від 200",
      "50 * 10%",
      "100 - 25%",
      "2,5%",
      "100% від 42",
      "# `у` rather than `в` before the cluster: Ukrainian alternates the two by",
      "# what surrounds them, and both are conversion keywords, so the corpus can",
      "# say the natural one.",
      "#",
      "# The spelled-out unit, which is where a language shows: `відсоток` and",
      "# `процент` are both current in Ukrainian and both read, and the printed",
      "# form stays the `%` sign in either case.",
      "10 відсотків",
      "10 процентів",
      "21 відсоток",
    ],
  },
  {
    pkg: "power",
    engine: createEngine({
      locales: [composeLocale(uk, [numberUk, powerUk])],
      kinds: [number, power],
    }),
    lines: [
      HEADER,
      "1 кВт в Вт",
      "1 МВт в кВт",
      "1 кс в Вт",
      "500 Вт + 500 Вт",
      "2 кВт - 500 Вт",
      "3 кВт * 2",
      "1 МВт / 4",
      "-1 кВт",
      "1000 Вт в кВт",
      "один кіловат",
      "2,5 кВт",
      "746 Вт в кс",
      "1 ГВт в МВт",
      "100 Вт",
      "1,5 МВт в Вт",
      "# Horsepower is `кінська сила` in full, two words, so the vocabulary's",
      "# symbol is the abbreviation `кс` — a printed phrase would be unreadable",
      "# back, which is the failure `assertLocaleContract` names.",
      "1 кс",
      "2 кс",
      "# The declined watt, all four categories.",
      "21 ват",
      "11 ватів",
      "2 вати",
      "500 Вт + 250 Вт",
    ],
  },
  {
    pkg: "speed",
    engine: createEngine({
      locales: [composeLocale(uk, [numberUk, lengthUk, durationUk, speedUk])],
      kinds: [number, length, duration, speed],
    }),
    lines: [
      HEADER,
      "100 км / 2 год",
      "100 kph в mph",
      "60 mph в kph",
      "1 вузол в kph",
      "10 mps в kph",
      "50 kph + 50 kph",
      "100 kph - 20 kph",
      "30 kph * 2",
      "100 kph / 4",
      "-10 kph",
      "1 км / 1 хв",
      "один kph",
      "3,6 kph в mps",
      "120 kph",
      "5 mps",
      "# The three composed units have no Cyrillic alias — their words *are*",
      "# operators (`км/год`, `м/с`), so the lexer ends the token at the slash and",
      "# no alias index can hold them. That is why they read as arithmetic over",
      "# length and duration instead, which is the row below, and why the knot —",
      "# the one unit that is a noun — is the one with Ukrainian words.",
      "120 км/год",
      "2 вузли",
      "5 вузлів",
      "21 вузол",
    ],
  },
  {
    pkg: "temperature",
    engine: createEngine({
      locales: [composeLocale(uk, [numberUk, ...temperatureUk])],
      kinds: [number, temperature, tempdelta],
    }),
    lines: [
      HEADER,
      "212 F в C",
      "0 C в F",
      "100 C в K",
      "0 K в C",
      "30 C - 20 C",
      "20 C",
      "98,6 F в C",
      "-40 C в F",
      "37 C в F",
      "273,15 K в C",
      "10 C + 5 C",
      "1 C",
      "72 F",
      "300 K",
      "-10 C в K",
      "# The scales spelled out. A Ukrainian reader writes `20 цельсія`, and the",
      "# printed answer stays the degree symbol in both languages — a scale is one",
      "# of the few units whose symbol is not a translation of anything.",
      "20 цельсія",
      "300 кельвінів",
      "72 фаренгейта",
      "# The decimal comma on a temperature, where English's period would be.",
      "36,6 C",
    ],
  },
  {
    pkg: "tempo",
    engine: createEngine({
      locales: [composeLocale(uk, [numberUk, durationUk, tempoUk])],
      kinds: [number, duration, tempo],
    }),
    lines: [
      HEADER,
      "120 бпм",
      "120 бпм в мс",
      "120 бпм в с",
      "500 мс в бпм",
      "1 с в бпм",
      "60 бпм в с",
      "2 гц в бпм",
      "120 бпм в гц",
      "120 бпм + 8 бпм",
      "140 бпм - 20 бпм",
      "60 бпм * 2",
      "120 бпм / 2",
      "-10 бпм",
      "один бпм",
      "174 бпм",
      "# `уд` — beats — is what a Ukrainian musician actually writes, and it is an",
      "# alias for the same unit the Latin `bpm` names.",
      "120 уд",
      "2 герци",
      "5 герців",
    ],
  },
  {
    pkg: "volume",
    engine: createEngine({
      locales: [composeLocale(uk, [numberUk, volumeUk])],
      kinds: [number, volume],
    }),
    lines: [
      HEADER,
      "1 л в мл",
      "1 м3 в л",
      "1 гал в л",
      "1 пінта в мл",
      "500 мл + 500 мл",
      "2 л - 250 мл",
      "3 л * 4",
      "1 л / 4",
      "-2 л",
      "1000 мл в л",
      "один літр",
      "1 гал в пінтах",
      "2 пінти в л",
      "1,5 л",
      "250 мл в л",
      "# `пінта` is feminine and `літр` masculine, so the fractional row differs",
      '# between them: "1,5 літра" is a genitive singular that is not the',
      '# nominative plural, and "1,5 пінти" is one that is.',
      "21 літр",
      "11 літрів",
      "2 літри",
      "2 пінти",
      "5 пінт",
      "# `кубометр` written out, which is how the cubic metre is said rather than",
      "# printed — the symbol stays `м³`.",
      "2 кубометри",
    ],
  },
];

for (const { pkg, engine, lines } of CORPORA) {
  const out: string[] = [];
  for (const line of lines) {
    if (line.startsWith("#")) {
      out.push(line);
      continue;
    }
    const r = engine.evaluate(line);
    out.push([line, r.kind, r.value.canonical.toString(), r.formatted].join("\t"));
  }
  const url = new URL(`../../${pkg}/corpus/uk.tsv`, import.meta.url);
  await Bun.write(url, `${out.join("\n")}\n`);
  console.log(`${pkg}: ${out.filter((l) => !l.startsWith("#")).length} rows`);
}
