// Generated by @smartput/query-introspect from a postgres catalogue (shop, schema public).
//
// This file is yours. Edit it, commit it, and keep editing it: regeneration
// refuses to overwrite it without --force, and `--check` reads it back and
// compares it against the live database, so a migration cannot walk away from it
// unnoticed.
//
// What a catalogue proves is here: table and column names, primary keys, foreign
// keys as join edges, enumerated values, and the two kinds a type settles —
// `datetime` for a timestamp and `date` for a date.
//
// What it cannot prove is not here, and no version of it was guessed. Every ratio
// kind — money, mass, percent — needs a unit, and nothing in a catalogue says
// whether `total_cents` counts money or counts cents. Nor are the words people
// type: `aliases`, `labels` and `metrics` decide whether a sentence links at all,
// and they are a human's to write.
//
// The TODO lines below are name-shaped hints, never applied. To answer one
// permanently, put the answer in the database, where regeneration cannot lose it:
//
//   COMMENT ON COLUMN orders.total_cents IS
//     '@smartput kind=money unit=usd scale=100 aliases=total, amount';

import { defineSchema, type Schema } from "@smartput/query";

export const schema: Schema = defineSchema({
  tables: [
    {
      name: "addresses",
      key: "id",
      columns: [
        { name: "id", as: "number" },
        { name: "customer_id", as: "number" },
        { name: "line1", as: "string" },
        { name: "lat", as: "number" },
        { name: "lon", as: "number" },
      ],
      // TODO: `lat`/`lon` look like a position. Declaring
      // geo: { lat: "lat", lon: "lon" } is what turns on `near`.
    },
    {
      name: "customers",
      key: "id",
      columns: [
        { name: "id", as: "number" },
        { name: "name", as: "string" },
        { name: "email", as: "string" },
        { name: "country_code", aliases: ["country"], kind: "place" },
        { name: "created_at", kind: "datetime" },
        { name: "tier", as: "string", values: ["free", "gold", "platinum"] },
        // TODO: `_cents` suggests { kind: "money", unit: "<iso4217>", scale: 100 }
        { name: "lifetime_cents", as: "number" },
      ],
    },
    {
      // TODO: the primary key is (order_id, line_no). TableDef.key names
      // one column — it is what `count` counts and what an aggregate groups by.
      name: "order_lines",
      key: "order_id",
      columns: [
        { name: "order_id", as: "number" },
        { name: "line_no", as: "number" },
        { name: "sku", as: "string" },
        { name: "qty", as: "number" },
      ],
    },
    {
      name: "orders",
      aliases: ["order", "purchase", "sale", "sales"],
      key: "id",
      columns: [
        { name: "id", as: "number" },
        { name: "customer_id", as: "number" },
        { name: "billing_address_id", as: "number" },
        { name: "shipping_address_id", as: "number" },
        {
          name: "status",
          as: "string",
          values: ["pending", "paid", "shipped", "cancelled"],
        },
        {
          name: "total_cents",
          aliases: ["total", "amount"],
          kind: "money",
          unit: "usd",
          scale: 100,
        },
        // TODO: `_g` suggests { kind: "mass", unit: "g" }
        { name: "weight_g", as: "number" },
        // TODO: `_rate` suggests { kind: "percent", unit: "%" }
        // — a column storing 0.15 rather than 15 also wants `scale: 0.01`.
        { name: "discount_rate", as: "number" },
        { name: "placed_at", kind: "datetime" },
        { name: "delivered_on", kind: "date" },
        { name: "is_gift", as: "boolean" },
        { name: "note", as: "string" },
        // TODO: `jsonb` has no ColumnDef binding here. Give it an `as`
        // if a driver hands it back as a number, string, boolean or Date.
        { name: "metadata" },
      ],
    },
  ],
  joins: [
    { from: "addresses.customer_id", to: "customers.id" },
    { from: "order_lines.order_id", to: "orders.id" },
    { from: "orders.billing_address_id", to: "addresses.id" },
    { from: "orders.customer_id", to: "customers.id" },
    { from: "orders.shipping_address_id", to: "addresses.id" },
  ],
  // Nobody types `sum of total_cents`; they type `revenue`. A metric is the name
  // your team already uses, and no catalogue holds one.
  //
  // metrics: [
  //   { name: "revenue", aliases: ["spend"], fn: "sum", column: "orders.total_cents" },
  //   { name: "order_count", fn: "count", table: "orders" },
  // ],
});
